<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Repositories\Team\ReadOnly\**" />
    <Content Remove="Repositories\Team\ReadOnly\**" />
    <EmbeddedResource Remove="Repositories\Team\ReadOnly\**" />
    <None Remove="Repositories\Team\ReadOnly\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\Campaign.Shared\Campaign.Shared.csproj" />
  </ItemGroup>

</Project>
