// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Oracle.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Campaign.Shared.DataBaseContext.Entities;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Campaign.Shared.Migrations
{
    [DbContext(typeof(CampaingContextDb))]
    [Migration("20260318181109_AddUserTable")]
    partial class AddUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("HOMOLOGA")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Campaign.API.Configuration.DataBaseContext.Entites.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("CF_CAMPANHA_EQUIPE", "HOMOLOGA");
                });

            modelBuilder.Entity("Campaign.API.Configuration.DataBaseContext.Entites.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("LastAccess")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ULTIMO_ACESSO");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("GERENTE_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SENHA");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ROLE");

                    b.Property<int>("TeamId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EQUIPE_ID");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("CF_CAMPANHA_USUARIO", "HOMOLOGA");
                });

            modelBuilder.Entity("Campaign.API.Configuration.DataBaseContext.Entites.User", b =>
                {
                    b.HasOne("Campaign.API.Configuration.DataBaseContext.Entites.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.HasOne("Campaign.API.Configuration.DataBaseContext.Entites.Team", "Team")
                        .WithOne()
                        .HasForeignKey("Campaign.API.Configuration.DataBaseContext.Entites.User", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
