// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Oracle.EntityFrameworkCore.Metadata;
using Campaign.Shared.DataBaseContext.Entities;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Campaign.Shared.Migrations
{
    [DbContext(typeof(CampaingContextDb))]
    [Migration("20260318192921_AdicionadoMudancasNasTabelasDeUsuarioETime")]
    partial class AdicionadoMudancasNasTabelasDeUsuarioETime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("HOMOLOGA")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Campaign.API.Configuration.DataBaseContext.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("CF_CAMPANHA_EQUIPE", "HOMOLOGA");
                });

            modelBuilder.Entity("Campaign.API.Configuration.DataBaseContext.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("LastAccess")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ULTIMO_ACESSO");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("GERENTE_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("SENHA");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ROLE");

                    b.Property<int>("TeamId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EQUIPE_ID");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId")
                        .IsUnique()
                        .HasFilter("\"GERENTE_ID\" IS NOT NULL");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("CF_CAMPANHA_USUARIO", "HOMOLOGA");
                });

            modelBuilder.Entity("Campaign.API.Configuration.DataBaseContext.Entities.User", b =>
                {
                    b.HasOne("Campaign.API.Configuration.DataBaseContext.Entities.User", "Manager")
                        .WithOne()
                        .HasForeignKey("Campaign.API.Configuration.DataBaseContext.Entities.User", "ManagerId");

                    b.HasOne("Campaign.API.Configuration.DataBaseContext.Entities.Team", "Team")
                        .WithOne()
                        .HasForeignKey("Campaign.API.Configuration.DataBaseContext.Entities.User", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
