// <auto-generated />
using System;
using Campaign.Shared.DataBaseContext.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Campaign.Shared.Migrations
{
    [DbContext(typeof(CampaingContextDb))]
    [Migration("20260324193451_AddTablePromotionReadDataHistory")]
    partial class AddTablePromotionReadDataHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("HOMOLOGA")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Campaign.Shared.DataBaseContext.Entities.Branch", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("CODIGO");

                    b.HasKey("Id");

                    b.ToTable("PCFILIAL", "HOMOLOGA", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Campaign.Shared.DataBaseContext.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODCLI");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("PCCLIENT", "HOMOLOGA", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Campaign.Shared.DataBaseContext.Entities.OrderDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMPED");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODCLI");

                    b.Property<int>("Price")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PVENDA");

                    b.Property<int>("ProductId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODPROD");

                    b.Property<long>("Quantity")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("QT");

                    b.HasKey("Id");

                    b.ToTable("PCPEDI", "HOMOLOGA", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Campaign.Shared.DataBaseContext.Entities.OrderSummary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NUMPED");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BranchId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("CODFILIAL");

                    b.Property<int>("CustomerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODCLI");

                    b.Property<DateTime>("DateOfSale")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA");

                    b.Property<int>("SellerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODUSUR");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.HasIndex("SellerId")
                        .IsUnique();

                    b.ToTable("PCPEDC", "HOMOLOGA", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Campaign.Shared.DataBaseContext.Entities.ProductPromotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("REP_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("REP_DATA");

                    b.Property<decimal>("MaxPointsValue")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("VLCADAPONTO");

                    b.Property<decimal>("MinPointsValue")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("QTPONTOSPESO");

                    b.Property<int>("ProductId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODPROD");

                    b.Property<int>("PromotionCode")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODPROMOCAO");

                    b.Property<int>("QuantityGoals")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QTMETA");

                    b.Property<decimal>("QuantityMinItem")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("QTMINITEM");

                    b.Property<decimal>("QuantityMinWeightPoints")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("QTPESOMINIMOPONTUACAO");

                    b.Property<decimal>("QuantityPoints")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("QTPONTOS");

                    b.Property<decimal>("QuantityPointsGoals")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("QTPONTOSCLIENTE");

                    b.Property<decimal>("QuantityPointsValue")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("QTPONTOSVALOR");

                    b.Property<decimal>("QuantityPointsWeight")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("QTMAXPONTO");

                    b.Property<decimal>("ValuePoints")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("QTPONTOSMETA");

                    b.HasKey("Id");

                    b.ToTable("PCPROMOI", "HOMOLOGA", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Campaign.Shared.DataBaseContext.Entities.PromotionReadDataHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PromotionCode")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODPROMOCAO");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_LEITURA");

                    b.HasKey("Id");

                    b.ToTable("CF_CAMPANHA_PROMOI_HISTORICO_LEITURA", "HOMOLOGA");
                });

            modelBuilder.Entity("Campaign.Shared.DataBaseContext.Entities.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODUSUR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("PCUSUARI", "HOMOLOGA", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Campaign.Shared.DataBaseContext.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("CF_CAMPANHA_EQUIPE", "HOMOLOGA");
                });

            modelBuilder.Entity("Campaign.Shared.DataBaseContext.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("CPF");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("SENHA_CRIPTOGRAFADA");

                    b.Property<DateTime?>("LastAccess")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ULTIMO_ACESSO");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("GERENTE_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ROLE");

                    b.Property<int>("TeamId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EQUIPE_ID");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId")
                        .IsUnique()
                        .HasFilter("\"GERENTE_ID\" IS NOT NULL");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("CF_CAMPANHA_USUARIO", "HOMOLOGA");
                });

            modelBuilder.Entity("Campaign.Shared.DataBaseContext.Entities.OrderSummary", b =>
                {
                    b.HasOne("Campaign.Shared.DataBaseContext.Entities.Branch", "Branch")
                        .WithOne()
                        .HasForeignKey("Campaign.Shared.DataBaseContext.Entities.OrderSummary", "BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Campaign.Shared.DataBaseContext.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Campaign.Shared.DataBaseContext.Entities.Seller", "Seller")
                        .WithOne()
                        .HasForeignKey("Campaign.Shared.DataBaseContext.Entities.OrderSummary", "SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Customer");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Campaign.Shared.DataBaseContext.Entities.Users.User", b =>
                {
                    b.HasOne("Campaign.Shared.DataBaseContext.Entities.Users.User", "Manager")
                        .WithOne()
                        .HasForeignKey("Campaign.Shared.DataBaseContext.Entities.Users.User", "ManagerId");

                    b.HasOne("Campaign.Shared.DataBaseContext.Entities.Team", "Team")
                        .WithOne()
                        .HasForeignKey("Campaign.Shared.DataBaseContext.Entities.Users.User", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
