<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b88fc855-8a0c-407a-b6c7-a4232656b2bd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Commands\SllerScore\**" />
    <Compile Remove="Orchestrators\CalculateScore\Validators\**" />
    <Compile Remove="Repositories\OrderDetail\WriteOnly\**" />
    <Compile Remove="Repositories\OrderSummary\WriteOnly\**" />
    <Compile Remove="Repositories\ProductPromotion\WriteOnly\**" />
    <Compile Remove="Repositories\Sellers\Seller\WriteOnly\**" />
    <Content Remove="Commands\SllerScore\**" />
    <Content Remove="Orchestrators\CalculateScore\Validators\**" />
    <Content Remove="Repositories\OrderDetail\WriteOnly\**" />
    <Content Remove="Repositories\OrderSummary\WriteOnly\**" />
    <Content Remove="Repositories\ProductPromotion\WriteOnly\**" />
    <Content Remove="Repositories\Sellers\Seller\WriteOnly\**" />
    <EmbeddedResource Remove="Commands\SllerScore\**" />
    <EmbeddedResource Remove="Orchestrators\CalculateScore\Validators\**" />
    <EmbeddedResource Remove="Repositories\OrderDetail\WriteOnly\**" />
    <EmbeddedResource Remove="Repositories\OrderSummary\WriteOnly\**" />
    <EmbeddedResource Remove="Repositories\ProductPromotion\WriteOnly\**" />
    <EmbeddedResource Remove="Repositories\Sellers\Seller\WriteOnly\**" />
    <None Remove="Commands\SllerScore\**" />
    <None Remove="Orchestrators\CalculateScore\Validators\**" />
    <None Remove="Repositories\OrderDetail\WriteOnly\**" />
    <None Remove="Repositories\OrderSummary\WriteOnly\**" />
    <None Remove="Repositories\ProductPromotion\WriteOnly\**" />
    <None Remove="Repositories\Sellers\Seller\WriteOnly\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\Campaign.Shared\Campaign.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Repositories\SellerScoreProductsSummary\ReadOnly\" />
  </ItemGroup>

</Project>
